# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    image: s3rg/openvpn
    cap_add:
        - NET_ADMIN
    ports:
        - 443:443/tcp
    environment:
        HOST_ADDR: ${HOST_ADDR} 
    volumes:
        - ./openvpn_conf:/doc/Dockovpn
    restart: always
